# Set library path for libsctp at runtime.
#   LD_LIBRARY_PATH=/usr/local/lib
# 


all: 
	gcc -Wall -lsctp -o bursttest_client bursttest_client.c
	gcc -Wall -lsctp -o bursttest_server bursttest_server.c
