#!/usr/bin/perl

use IO::Socket;
use IO::Select;
use IO::Handle;



$mount_stat = `rsh 192.168.1.2 df | grep DATA1`;
if ($mount_stat =~ /DATA1/) {
	$target_addr = "192.168.1.2";
}
else {
	$target_addr = "192.168.1.12";
}


local $| = 1;

$sock_target = IO::Socket::INET->new(
	PeerAddr   => ${target_addr} . ":61500",
	Proto      => "tcp",
	Reuse      => 1
) or die "sock_target connect fail. $!\n";



$readset = IO::Select->new();
$readset->add(*STDIN);
$readset->add($sock_target);

while (1) {
	@ready = $readset->can_read;
	foreach $fh (@ready) {
		if ($fh == STDIN) {
			$data = <STDIN>;
			close_exit() if length($data) == 0;
			$sock_target->send($data);
		}
		if ($fh == $sock_target) {
			$sock_target->recv($data, 65535);
			close_exit() if length($data) == 0;
			print $data;
		}
	}
}


sub close_exit {
	$sock_target->close();
	close(STDIN);
	close(STDOUT);
	sleep(1);
	exit(1);
}

$SIG{'INT'}  = \&close_exit();
$SIG{'KILL'} = \&close_exit();
$SIG{'PIPE'} = \&close_exit();



